apiVersion: v1
binaryData:
  pmu.bin: MTUwMDAKNDcxMgpDRkcgMSAxMzQKqjEAhgAIaW+hOwBGCpUA////AAFwbXUtOCAgICAgICAgICAgAAgADwADAAEAAFZfQSAgICAgICAgICAgICBWX0IgICAgICAgICAgICAgVl9DICAgICAgICAgICAgIFAgICAgICAgICAgICAgICAAAAABAAAAAQAAAAECAAABAAEAAAAZWR4K
kind: ConfigMap
metadata:
  name: pmu-8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmu-8
spec:
  selector:
    matchLabels:
      app: pmu-8
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pmu-8
    spec:
      containers:
      - name: pmu
        image: harbor.crownlabs.polito.it/cloud-sandbox/s333985/claudious96/pmu-cli@sha256:bcc5fe2237ed113266e09d0d0b20b05101a2e03b63d8fe4776084cc12ece248b
        command: [ "PMU", "-i", "pmu.bin" ]
        ports:
        - containerPort: 4712
        env:
        - name: TERM
          value: xterm
        volumeMounts:
        - name: pmu-8
          mountPath: /pmu.bin
          subPath: pmu.bin
        livenessProbe:
          tcpSocket:
            port: 4712
          initialDelaySeconds: 15
          periodSeconds: 20

      volumes:
        - name: pmu-8
          configMap:
            name: pmu-8
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pmu-8
  labels:
    name: pmu-8
spec:
  selector:
    app: pmu-8
  ports:
    - protocol: TCP
      port: 4712
      targetPort: 4712