apiVersion: v1
binaryData:
  pmu.bin: MTUwMDAKNDcxMgpDRkcgMSAxMzQKqjEAhgAGaW9y5ADTiggA////AAFwbXUtNiAgICAgICAgICAgAAYADgADAAEAAFZfQSAgICAgICAgICAgICBWX0IgICAgICAgICAgICAgVl9DICAgICAgICAgICAgIFAgICAgICAgICAgICAgICAAAAABAAAAAQAAAAECAAABAAEAAAAZy3YK
kind: ConfigMap
metadata:
  name: pmu-6
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmu-6
spec:
  selector:
    matchLabels:
      app: pmu-6
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pmu-6
    spec:
      containers:
      - name: pmu
        image: claudious96/pmu-cli
        command: [ "PMU", "-i", "pmu.bin" ]
        ports:
        - containerPort: 4712
        env:
        - name: TERM
          value: xterm
        volumeMounts:
        - name: pmu-6
          mountPath: /pmu.bin
          subPath: pmu.bin
        livenessProbe:
          tcpSocket:
            port: 4712
          initialDelaySeconds: 15
          periodSeconds: 20

      volumes:
        - name: pmu-6
          configMap:
            name: pmu-6
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pmu-6
  labels:
    name: pmu-6
spec:
  selector:
    app: pmu-6
  ports:
    - protocol: TCP
      port: 4712
      targetPort: 4712